version: '3.9'

services:

  backend:

    build:
      context: ..
      dockerfile: docker/backend.Dockerfile

    container_name: driftguard_backend

    ports:
      - "8000:8000"

    restart: always


  frontend:

    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile

    container_name: driftguard_frontend

    ports:
      - "8501:8501"

    depends_on:
      - backend

    restart: always